# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d05e73b063693aa833df9790f95a8c7d6898fa3653a4fff6bfe62194a7de3eccf94e1884f0f2a5e9b577ebc3d7ffdaf890791d94dbdcd705ea0441e16da3869

test:
  secret_key_base: 8a0fa72fff682c64732178f6f2a3a7706694bf412a943b025176f7c4adafc243b3789fd175cb46e73a24599f73b4eacde48bbf0eae7f6dffbf089230f39ae7f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
